= {CPP} Ecosystem IS Open License
:copyright: Copyright {docyear} René Ferdinand Rivera Morell, Jayesh Badwaik
:license: Creative Commons Attribution 4.0 International License (CC BY 4.0)
:email: grafikrobot@gmail.com, jayesh@badwaik.dev
:authors: René Ferdinand Rivera Morell, Jayesh Badwaik
:audience: WG21
:revdate: {docdate}
:version-label!:
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 10
:source-highlighter: rouge
:source-language: {CPP}
:toc: left
:toclevels: 2
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:table-caption: Table
:opt: opt

++++
<style>
include::../std-min.css[]
</style>
++++

[horizontal]
Document #: :: ISO/IEC/JTC1/SC22/WG21/{revnumber}
Date: :: {revdate}
Audience: :: {audience}
Authors: :: {authors}
Reply-to: :: {email}
Copyright: :: {copyright}, {license}


== Abstract

In this paper, we advocate for the {CPP} Ecosystem IS (EcoIS) to adopt a CC-BY
license for the development and publication of the standard in order to allow
for seamless use of the standard by the community and to facilitate community
contributions back to the standard. We outline the proposals and explain how it
fits within the current copyright policy of the ISO.


== Revision History

=== Revision 0 (June 2024)

Initial text.


== Motivation

EcoIS aims to facilitate the interoperation of tools and systems that
implement, and interface with, the {CPP} International Standard (ISO/IEC
14882). The ecosystem of tools and systems is quite diverse and evolving
swiftly in response to evolving technologies and user needs. Furthermore, a
significant portion of the tools and systems are developed by loosely formed
communities of developers across different countries and companies.

In order for the EcoIS to be effective, it must be able to incorporate the
ideas and experiences of the community in a timely manner without excessive
overhead. In particular, the community should be able to contribute to the
EcoIS and be able to then use EcoIS in their own ecosystems with as little
friction as possible.

The CC-BY license, created by the Creative Commons organization, allows one to
share and adapt licensed material as long as appropriate credit is given. Such
a license would allow the EcoIS to be developed and published in a way that is
open and free to use by the community. With such a license, the community will
be able to use the standard in their own tools and systems, and be able to
contribute back to the standard in a seamless manner.


== Proposal

Our proposal is to develop the EcoIS from individually copyrighted content with
a license that allows for unfettered use by ISO for development and commercial
use. Specifically it would be that:

. Individual Pnnnn papers would be copyrighted by the authors and licensed under
  the "Creative Commons Attribution 4.0 International License" (CC-BY-4.0).
  footnote:CCBY4[Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/)]
. The resulting EcoIS Nnnnn draft paper and published International Standard
  would be copyrighted by the collection of authors and ISO/IEC.
. The resulting EcoIS Nnnnn draft paper and published International Standard
  would be licensed under CC-BY-4.0 and include required attribution.


== ISO and Copyright

In this section, we justify the proposal under the current copyright policy of
the ISO. The main aspects of copyright policy that one must consider when
working on an ISO standard are outlined in _Declaration for participants in ISO
activities_
footnote:ISODeclaration[Declaration for participants in ISO activities (https://www.iso.org/declaration-for-participants-in-iso-activities.html)]
and in the _ISO/IEC Directives, Part 1_
footnote:ISODirectives[ISO/IEC Directives, Part 1 Procedures for the technical work — Consolidated ISO Supplement — Procedures specific to ISO (https://www.iso.org/directives-and-policies.html)]
which outlines the copyright policy for anyone involved in the ISO
standardization process.

The complete text of the section on copyright from  _Declaration for
participants in ISO activities_ footnote:ISODeclaration[] is reproduced here
for the reader's benefit, with the key parts underlined:

[quote,Declaration for participants in ISO activities]
____
+I+. Copyright

You may participate in drafting ISO and ISO/IEC standards and you may submit
content to the ISO and ISO/IEC standards development process. By participating
in the ISO standards development process you get access to all kinds of
information filed during this process such as standards and their drafts,
content, etc. Content can be any kind of content submitted in the standards
development process, such as publications, documents, text, figures, images,
software, etc., to be considered for inclusion in ISO and ISO/IEC standards.
You agree that:

1) The full copyright in all ISO standards and their drafts shall be owned by
ISO. In the case of ISO/IEC standards, such ownership shall be held jointly by
ISO and IEC.

[.underline]
2) Content, such as publications, documents, text, figures, images or other
content that you submit to the ISO or ISO/IEC standards development process
may be copyright protected. Copyright in such content remains with the initial
copyright owner. If you offer such content, you undertake to declare this to
ISO or ISO/IEC, identify the name of the copyright holder and assist ISO or
ISO/IEC in obtaining appropriate permission to i) share the content in the
standards development process, ii) to publish the content, or parts thereof,
in original or modified form in ISO or ISO/IEC standards and iii) to exploit
the content as part of an ISO or ISO/IEC standard according to ISO and IEC
practice. If you or the organization you are representing own/s the copyright
in the content, such permission is implicitly granted to ISO or ISO/IEC, upon
submission of the content to the standards development process. More details
about the scope of the above permission are available at
link:https://connect.iso.org/x/SYBGAQ[connect.iso.org/x/SYBGAQ].

3) You agree to respect copyright in the standards, draft standards, and
content of others submitted to the standards development process. You are
allowed to share the standards and drafts thereof within the standards
development process according to ISO's copyright policy, POCOSA. POCOSA does
not permit you to post standards and drafts thereof on the Internet for free
public access.

4) Participation in the drafting of the standards, and content to the
standards development process, are provided without any payment by ISO or IEC
to you or any third party.

5) Full copyright includes but is not limited to the exclusive right of
reproduction, distribution, making available to the public, translation,
adaptation, in any existing or future electronic or printed format, for the
entire term of copyright protection.
____


Let's break down the underlying text to understand the implications of the
copyright policy for the EcoIS.

[quote]
1) The full copyright in all ISO standards and their drafts shall be owned by
ISO. In the case of ISO/IEC standards, such ownership shall be held jointly by
ISO and IEC.

The sentence asserts that the full copyright for ISO standards is held by ISO.
And in the case of joint standards, the copyright is held jointly by ISO and
IEC.

In preparation for the arguments that follow, we note that it is not unusual in
the copyright law for the copyright holder to hold full copyright to only the
complete work, while the individual contributors can still hold a copyright to
their individual parts. In particular, it is possible for a document containing
the entire text of the EcoIS standard to be copyrighted by the collection of
authors, while the actual standard, as published, is copyrighted by ISO.


[quote]
Content, such as publications, documents, text, figures, images or other
content that you submit to the ISO or ISO/IEC standards development process
may be copyright protected.

The sentence provides the context under which the rest of the paragraph is
supposed to be applied. The sentence recognizes that parts, or even entirety,
of the content used for ISO standards can have an existing copyright. For
example, the copyright for such content could be held by an external standards
organization or by an individual person.

[quote]
Copyright in such content remains with the initial copyright owner.

The declaration asserts that, in such cases, the copyright remains with the
original copyright holder. Such an assertion is in line with the observation
made in a previous statement, that even though the ISO holds the full copyright
to the complete work, the individual contributors can still hold a copyright to
their individual contributions.

The assertion is further in line with the understood International Law that
copyright is not automatically transferred.

[quote]
If you offer such content, you undertake to declare this to ISO or ISO/IEC,
identify the name of the copyright holder and assist ISO or ISO/IEC in
obtaining appropriate permission to i) share the content in the standards
development process, ii) to publish the content, or parts thereof, in original
or modified form in ISO or ISO/IEC standards and iii) to exploit the content as
part of an ISO or ISO/IEC standard according to ISO and IEC practice.

This next rather long sentence essentially is a permissive license grant to ISO
that gives ISO the rights to use the contents in the manner specified above. We
note we do not have to use this specific license grant, and that any license
grant that allows ISO to use the content in the manner specified above is an
acceptable license grant for the ISO. In particular, we note that CC-BY is such
a license grant.

[quote]
If you or the organization you are representing own/s the copyright
in the content, such permission is implicitly granted to ISO or ISO/IEC, upon
submission of the content to the standards development process.

The above makes it rather simple to give ISO the appropriate license grant by
making it an implicit part of submitting content to ISO. We note that the
application of CC-BY license is compatible with this implicit grant.

The ISO/IEC Directives footnote:ISODirectives[] repeat the same information but
in less legally formal terms. Here's the relevant clause in that document with
similarly underlined text to highlight the important paragraphs.

[quote,ISO/IEC Directives, Part 1 Procedures for the technical work — Consolidated ISO Supplement — Procedures specific to ISO]
____
2.13 Copyright

The copyright for all drafts and International Standards and other publications
belongs to ISO, IEC or ISO and IEC, respectively as represented by the Office
of the CEO.

[.underline]
The content of, for example, an International Standard may originate from a
number of sources, including existing national standards, articles published in
scientific or trade journals, original research and development work,
descriptions of commercialized products, etc. These sources may be subject to
one or more rights.

[.underline]
In ISO and IEC, there is an understanding that original material contributed to
becoming a part of an ISO, IEC or ISO/IEC publication can be copied and
distributed within the ISO and/or IEC systems (as relevant) as part of the
consensus building process, this being without prejudice to the rights of the
original copyright owner to exploit the original text elsewhere. Where the
material is already subject to copyright, the right should be granted to ISO
and/or IEC to reproduce and circulate the material. This is frequently done
without recourse to a written agreement or, at most, to a simple written
statement of acceptance. Where contributors wish a formal signed agreement
concerning the copyright of any submissions they make to ISO and/or IEC, such
requests shall be addressed to ISO Central Secretariat or the IEC Secretariat,
respectively.

Attention is drawn to the fact that the respective members of ISO and IEC have
the right to adopt and re-publish any respective ISO and/or IEC document as
their national standard. Similar forms of endorsement do or may exist (for
example, with regional standardization organizations).
____

As you may have noticed an important condition to this alternative copyright
route to be available is for the paper, draft, etc to be originally copyrighted.
Which currently, for all the EcoIS content is the case. Including this very
paper that you are reading. See the following for such:

* link:https://wg21.link/P2717[P2717] SG15 Tooling: Tool Introspection
* link:https://wg21.link/P3051[P3051] SG15 Tooling: Structured Response Files

== License

This work is licensed under the Creative Commons Attribution 4.0 International
License. To view a copy of this license, visit
http://creativecommons.org/licenses/by/4.0/ or send a letter to Creative
Commons, PO Box 1866, Mountain View, CA 94042, USA.
