= Structured Response Files
:copyright: Copyright {docyear} René Ferdinand Rivera Morell
:license: Creative Commons Attribution 4.0 International License (CC BY 4.0)
:email: grafikrobot@gmail.com
:authors: René Ferdinand Rivera Morell
:audience: SG15
:revdate: {docdate}
:version-label!:
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 10
:source-highlighter: rouge
:source-language: {CPP}
:toc: left
:toclevels: 2
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:table-caption: Table
:opt: opt

++++
<style>
include::../std-min.css[]
</style>
++++

[horizontal]
Document #: :: ISO/IEC/JTC1/SC22/WG21/{revnumber}
Date: :: {revdate}
Audience: :: {audience}
Authors: :: {authors}
Reply-to: :: {email}
Copyright: :: {copyright}, {license}


== Abstract

This aims to define a standard structured response file format that can become
the best way to communicate compiling {CPP}.


== Revision History

=== Revision 1 (May 2024)

Specify that `options` use abstract features instead of literal arguments, per
SG15 feedback. Addition of wording.

=== Revision 0 (December 2023)

Initial text.


== Motivation

A key aspect of inter-operation between tools in the ecosystem is having a
common language to express tool commands, i.e. in compiler drivers, that can
be understood and/or translated between different tools and platforms.

Currently tools use differing, but related, ways for users (and other tools) to
specify the set of options to "toolsets" (compiler drivers, linkers, etc).
While there are some commonalities in how those options are specified as
"configuration response files" containing bare options, there are sufficient
differences to hinder general inter-operation.


== Scope

This proposal aims to specify a method for tools to specify arguments to other
tools in a consistent and flexible manner. As such what it does and doesn't
aim to accomplish:

* It _does not_ aim to remove current arguments handling. It _does_ allow for
  incrementally adoption of an alternative that facilitates common tool
  arguments.

* It _does not_ specify any particular options to replace existing options
  (except the ones to indicate the new response file). It _does_ aim to
  specify an additional alternative option style that reduces the parsing
  complexity, and perhaps ambiguities, in tools.


== Current Response Files

Current response files commonly contain "unstructured" sequence of command line
arguments. Some also allow recursive inclusion and expansion of additional
response files. Below are a summary of the syntax, capabilities, and
restrictions of some of the compiler drivers.

=== Clang

* Use of `@__filename__` argument.
* Use of `--config=__filename__` argument.
* References to other response files allowed.

Example response file:

[source,{opt}]
----
# Several options on line
-c --target=x86_64-unknown-linux-gnu

# Long option split between lines
-I/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/C++/5.4.0

# other config files may be included
@linux.options
----

Source: Clang Compiler User’s Manual
footnote:Clang[Clang Compiler User’s Manual (https://clang.llvm.org/docs/UsersManual.html#configuration-files)]

==== GNU Compiler Collection, GCC

* Use of `@__filename__` argument.
* References to other response files allowed.

Example response file:

[source,{opt}]
----
-o "hello" -Wl,--start-group "bin/hello.o" -Wl,-Bstatic -Wl,-Bdynamic -Wl,--end-group -fPIC -g
----

Source: GCC Documentation
footnote:GCC[GCC Documentation (https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Overall-Options.html)]

=== Intel(R) oneAPI DP{CPP}/{CPP}

* Use of `@__filename__` argument.
* References to other response files disallowed.
* Platform specific option syntax.
* `#` prefixed line comments.

Example response file for "Linux":

[source,{opt}]
----
# compile with these options
  -O0
# end of response file
----

Example response file for "Windows":

[source,{opt}]
----
# compile with these options
  /0d
# end of response file
----

Source: Intel(R) oneAPI DP{CPP}/{CPP} Compiler Developer Guide and Reference
footnote:ICC[Intel(R) oneAPI DP{CPP}/{CPP} Compiler Developer Guide and Reference
(https://www.intel.com/content/dam/develop/external/us/en/documents/oneapi_dpcpp_cpp_compiler_2022.pdf)]

=== NVIDIA CUDA Compiler Driver NVCC

* Use of `--options-file __filename__,...`, or `-optf __filename__,...`.

[source,{opt}]
----
-O0
----

Source: NVIDIA CUDA Compiler Driver NVCC Documentation
footnote:NVCC[NVIDIA CUDA Compiler Driver NVCC Documentation
(https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html)]

=== Microsoft Visual {CPP}

* Use of `@__filename__` argument.
* References to other response files disallowed.

Example response file:

[source,{opt}]
----
"hello.cpp" -c -Fo"bin\hello.obj" -TP /wd4675 /EHs /GR /Zc:throwingNew /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend
----

Source: Microsoft {CPP}, C, and Assembler documentation
footnote:MSVC[Microsoft {CPP}, C, and Assembler documentation (https://learn.microsoft.com/en-us/cpp/build/reference/at-specify-a-compiler-response-file)]

=== Other

Edison Design Group {CPP} Front End (`edgcpfe`)::
  Does not support response configuration files.
  footnote:[Edison Design Group {CPP} documentation. https://www.edg.com/docs/edg_cpp.pdf]

Embarcadero {CPP} Builder::
  Supports at least `@__filename__` option, with bare arguments syntax.
  footnote:[B2 Embarcadero {CPP} Builder `@` file implementation. (https://github.com/bfgroup/b2/blob/4.10.1/src/tools/borland.jam#L282)]

IBM Open XL C/{CPP} for AIX 17.1.0::
  Supports the Clang footnote:Clang[] `--config` option.

IBM Open XL C/{CPP} for Linux on Power 17.1.1::
  Has migrated to using the Clang footnote:Clang[] toolchain and supports the
  same options.

IBM Open XL C/{CPP} and XL C/{CPP} for z/OS::
  Supports the Clang footnote:Clang[] `--config` option.

HPE Cray Programming Environment (CPE)::
  Support depends on the platform complier environment.

NVIDIA HPC {CPP} (NV{CPP})::
  Does not support response configuration files.
  footnote:[NVIDIA HPC {CPP} Reference (https://docs.nvidia.com/hpc-sdk/compilers/hpc-compilers-ref-guide/index.html)]

Oracle® Developer Studio 12.6::
  Supports a single global options configuration file, with bare arguments
  syntax.

Python `argparse` module::
  Supports arbitrarily character prefixed response files. Where the files, by
  default, contain an argument per line.
  footnote:[Python `argparse` module (https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars)]

== Design

Abstractly _response files_ are files in the operating system storage that
contain arguments and options in addition to the ones given directly in the
tool invocation. For this design we are going to refer to two different types
of ways to pass the information to the tools:

Arguments::
Arguments use the syntax that one would specify directly in the command line as
a user. This would be things like the `-O1` optimization flag argument.

Options::
Options are the conceptual flag option that the tool understands that does not
necessarily follow the same syntax as the flags specify in command line
_arguments_.

Using those two distinct definitions allows us to specify them differently in
the response file. Using _arguments_ we will follow the same existing command
line syntax. Keeping a form of compatibility with existing tools. But we would
then be restricted to that syntax. Using _options_ we can use a definition that
fits best with a structured data definition.

Last consideration is the choice of structured data format we will have in the
response files. Keeping with previous work and practice we will use JSON text
as that format.
footnote:EcoISIntropection[P2717 Tool Introspection (https://wg21.link/P2717)]
footnote:JSONCompileDb[JSON Compilation Database Format Specification (https://clang.llvm.org/docs/JSONCompilationDatabase.html)]

With that context, here are two example structured response files:

*Simple Arguments:*

[source,json]
----
include::example-01.json[]
----

*Structured Options:*

[source,json]
----
include::example-02.json[]
----

NOTE: The names and values in the `options` example is for exposition only. It
may not reflect the actual names and values as proposed, now or in the future.

The _simple arguments_ example shows specifying an "__arguments__" key with an
array of values corresponding to the regular command line arguments. This
mirrors what one would see in a JSON compilation database footnote:JSONCompileDb[].
This style has some advantages:

* There is a direct correlation with the JSON compilation database format which
  some tools support. Which would mean that they already have code to deal with
  the JSON loading and understanding of it.
* There's a direct mapping for regular command line arguments. Hence it will be
  less effort to support this style for tools.

And there are some disadvantages:

* The parsing of the arguments still has to happen to get at the option and
  value.
* It is subject to the same limitations of regular command line arguments. Like
  complexity and ambiguities of command line syntax.

The _structured options_ example shows specifying an "__options__" key with
an array of option names or option objects. Where the option objects contain an
option name and structured value. Some advantages of this style of structured
data are:

* The option names do not indicate a particular option prefix (i.e. `-`, `--`,
  `/`, etc) making it possible to use tool agnostic common names.
* The ability to use arrays, or possibly objects, for the option values allows
  for logical groupings avoiding extra tracking of such as is present in
  command line parsing of options.
* The names can be more descriptive, and hence easier for people to understand.

Some possible disadvantages:

* Tools will need an alternative path to understand the new options. Although
  hopefully this is balanced by the more direct availability of the values.
* If this style is also to be supported in the JSON compile database format it
  means more work to accomplish that. But again, the hope is that there is an
  easier mapping from internal structures to this format.

The design we are proposing has the following key points:

* The format of the file is well formed JSON text.
* The top level of that is a JSON object with one of, or both, _arguments_
  and _options_ fields.
* The addition of one command line option to specify the structured response
  file.
* The _arguments_ field has a single array value with string values.
* The _arguments_ values are single strings containing the same options as would
  be specified in the command line.
* The _arguments_ values can contain the option for other structure response
  files. Which will be recursively inserted at the location of the option.
* The _options_ field has an array of values for structured options.
* The _options_ values will follow an option specific schema.
* The _arguments_ are not specified, and as such are implementation defined.
* The _options_ are specified with both a schema and semantics for each.

=== Command Line

We propose to add a single new command line option as a requirement to
implementing this capability:

--
`$ tool --std-{opt}=__file__`
--

Or:

--
`$ tool -std-{opt}:__file__`
--

The `std-{opt}` command line option, which can be repeated, will read the
indicated file and parse the JSON text contents to configure the tool as needed.

=== File Format

The response file is a valid JSON text file with a single JSON object as the
root object. There are two mutually exclusive fields to specify the command
information: `arguments` or `options`.

There are two additional, optional, fields: `$schema` and `version`. The
`$schema` field points at the released JSON Schema.
footnote:jschema[JSON Schema: A Media Type for Describing JSON Documents (http://json-schema.org/latest/json-schema-core.html)]
The `version` field indicated the response format of the file. The version
number follows those specified in the capability introspection version
numbering and semantics.

The `arguments` field specifies a *single* array value of strings. Each string
array entry is a command line argument to be used directly by the tool. The
specific syntax of the arguments is up to the specific tool. For example a
compile invocation for GCC, and compatible compiler front-ends, would look like:

[source,json]
----
include::example-arguments.json[]
----

You can also include `--std-{opt}=__file__` options in the list of arguments to
include the arguments that are referenced in another response file, and so on.
For example, given a `common.json` response file as such:

[source,json]
----
include::example-args-recurse-common.json[]
----

One can refer to it in a main response file that compiles a {CPP} source file:

[source,json]
----
include::example-args-recurse-main.json[]
----

The effect is that the options in `common.json` are inserted in the arguments
array at the location of the `--std-{opt}=common.json` argument.

The `options` field specifies a *single* array value of options values. An
option value can be any value that follows the schema for the collection of
specified options.

When compared to having the `arguments` field there are more constraints to the
syntax of the options:

* The option names do not contain prefix characters (i.e. the `--`, `-`, `/`,
  etc) and without the value separator (i.e. `=`, `:`, etc).

Like the `arguments` field, additional response files can be inserted at the
indicated location by specifying a `{ "std.{opt}": "file.json" }` option.

Do note though that even though the option names have a specific naming format
they are still defined by the tool. The goal of having the restrictions on the
option names is to make it possible in the future to specify tool agnostic
options to facilitate general interop. But that is a subject for future
proposals.

IMPORTANT: Tools need to support being able to either refer to an `options`
style response file from an `arguments` style response file, and conversely.

=== Flags or Names

There is a question as to wether it's better to use command line flags (for
example `W`, `o`, `I`, etc) or non-command line names (for example
`warning`, `output`, `include`, etc) in the `options` field. We will call the
former the "Flags" choice, and the latter the "Names" choice. Each would mean:

Flags::
	The keys would be direct correlation to the specific tool, i.e. compiler,
	command line options. For example a `I` field name would match the `-I`.

Names::
	The keys would be symbolic names correlating to a concept that may map to
	one or more current command line options. For example an `include` field
	name would map to one or more `-I` command line options. But it would also
	map to one or more new `--include` command line options.

Given those definitions we can consider the pros and cons of each method.

[cols=",50,50",options="header"]
|===
| ^| Flags ^| Names

^.^h| Pros

a| // Pros: Flags
* Small effort for compilers to implement.
* No additional CLI parsing to implement.

a| // Pros: Names
* Common names and meanings across different tools.
* Names could be used in other formats, like CPS.

^.^h| Cons

a| // Cons: Flags
* Continues the increased implementation burden on build systems, etc, to manage
  different options per compiler, etc.

a| // Cons: Names
* Possibly complex implementation to map from names to internal data.

|===

NOTE: One key consideration is that this proposal does not prevent choosing
either flags or names as the `options` fields. Specifying the fields can be
accomplished in a further proposal that specifies either flags or names as
common specified syntax.

There are a set of possible design questions for this proposal that come to
mind:

. Specify `options` fields as "Flags" or "Names"?
. Specify the `options` in this proposal or a separate proposal?

The discussions in WG21/SG15 concluded that it's preferable to use "names" for
the keys. This allows, as outlined in previous sections, a dual operation. The
"arguments" for some form of backward compatibility. And the "options" for
the modern structure tool invocation.

== Questions

Why use a new option (`--std-{opt}=__file__`) instead of existing response file methods like `@__file__`?::

Implementing support in tools for using the same response file options would:
* Mean that the option to add the structured response files would vary from
  tool to tool as some use different styles for specifying the file.
* It would be harder to implement as it would require inspecting the file
  content to determine the parsing method needed.

Why have an `arguments` field instead of just using the `options` field?::

Having an `arguments` field has a couple of benefits:
* It makes it easier for tools to immediately support use of this format as they
  can directly inject the arguments into their existing command line argument
  parsing.
* Makes it easier for tools that already support `compile_commands.json` to
  produce or consume structured response files as they are the same format for
  the `arguments` field in both.


== Polls

=== SG15: P3051R0 (2034-03-19)

SG15 wants to pursue defining a common response file format starting with
supporting utf8 simple command lines, accepting the limitations for
non-unicode arguments for the first version.

[options="header,autowidth",cols="^0,^0,^0,^0,^0"]
|===
| SF | F | N | A | SA
| 6  | 6 | 0 | 0 | 0
|===

Result: Consensus

SG15 wants to persue defining common structured tool configuration arguments as
part of the response file format.

[options="header,autowidth",cols="^0,^0,^0,^0,^0"]
|===
| SF | F | N | A | SA
| 6  | 3 | 3 | 0 | 0
|===

Result: Consensus

== Wording

Wording is relative to
link:https://github.com/cplusplus/ecosystem-is/tree/56aeadb86d52a15aa4ec948a1eb8f247a8b703d8[ecosystem-is/56aeadb].
footnote:[Working Draft, {CPP} Ecosystem International Standard 2023-11-10 (https://github.com/cplusplus/ecosystem-is/tree/56aeadb86d52a15aa4ec948a1eb8f247a8b703d8)]

=== Specification: Structured Options

Insert clause after _Introspection_ [intspct].

[.ins.text-justify]
[#strctopt,reftext=strctopt]
==== Structured Options [.right]#[<<strctopt>>]#

[#strctopt-pre,reftext=strctopt.pre]
===== Preamble [.right]#[<<strctopt-pre>>]#

This clause describes options, output, and formats that control the behavior
of applications through the specification of arguments and options from
_structured options_.

This clause specifies the `std.strctopt` capability ([intspct.cap]) version
`1.0.0`.

An application can implement this capability.

An application that implements the `std.strctopt` capability shall include the
`std.strctopt` field and version value in the introspection JSON text output
([intspct.schema.cap]).

[.ins.text-justify]
[#strctopt-overview,reftext=strctopt.overview]
==== Overview [.right]#[<<strctopt-overview>>]#

--
`_application_ [ __std-strctopt-input-opt__ __file__ ]`
--

[#strctopt-options,reftext=strctopt.options]
===== Options [.right]#[<<strctopt-options>>]#

Applications shall accept one of two options syntax variations: `--name=value`
or `-name:value`.

Applications shall indicate an error if invoked with an option syntax variation
that it does not support.

[#strctopt-opt-input,reftext=strctopt.opt.input]
===== Input Option [.right]#[<<strctopt-opt-input>>]#

`__std-strctopt-input-opt__`::
The pathname of a file to read the _structured options_ from.
The option is specified as `--std-{opt}=__file__` or `-std-{opt}:__file__`.
If __file__ is '`-`', the standard input shall be used.

[#strctopt-file,reftext=strctopt.file]
===== Files [.right]#[<<strctopt-file>>]#

An application shall read a valid JSON text file that conforms to the
_structured options_ schema (<<strctopt-schema>>).

An application shall interpret the information in the file as if the options
and arguments in the file occur in the same position as the
`__std-strctopt-input-opt__` argument of the list of arguments given to the
application. Given either directly as part of the application command line or
as part of the arguments field (<<strctopt-field-args>>).

[#strctopt-schema,reftext=strctopt.schema]
===== Schema [.right]#[<<strctopt-schema>>]#

A _structured options_ JSON text file shall contain one _structured options_
JSON object (<<strctopt-schema-obj>>).

[#strctopt-schema-obj,reftext=strctopt.schema.obj]
====== Structured Options Object [.right]#[<<strctopt-schema-obj>>]#

The _structured options object_ is the root JSON object of the structured
options JSON text.

A _structure options object_ can have the following fields.

[#strctopt-field-schema,reftext=strctopt.schema.schema]
====== JSON Schema Field [.right]#[<<strctopt-field-schema>>]#

_Name_: `$schema` +
_Type_: `string` +
_Value_:
  The value shall be a reference to a JSON Schema specification. +
_Description_:
  A _structure options object_ can contain this field.
  If a _structure options object_ does not contain this field the value shall
  be a reference to the JSON Schema corresponding to the current edition of this
  standard.

[#strctopt-field-ver,reftext=strctopt.schema.ver]
====== Version Field [.right]#[<<strctopt-field-ver>>]#

_Name_: `version` +
_Type_: `string` +
_Value_: `1` or `1.0` or `1.0.0` +
_Description_:
  The version field indicates the version of the _structured options_
  represented in the contents of the JSON text.

[#strctopt-field-args,reftext=strctopt.schema.args]
====== Arguments Field [.right]#[<<strctopt-field-args>>]#

_Name_: `arguments` +
_Type_: `array` +
_Value_:
  The value shall be a JSON `array`. The items in the `array` shall be of JSON
  `string` types.
_Description_:
  The arguments field specifies items to be interpreted directly as if they
  occur in the command line of the program.

The application shall process the items as if they replace the
`__std-strctopt-input-opt__` argument.

[#strctopt-field-opts,reftext=strctopt.schema.opts]
====== Options Field [.right]#[<<strctopt-field-opts>>]#

_Name_: `options` +
_Type_: `array` +
_Value_:
  The value shall be a JSON `array`. The items in the `array` shall be of either
  JSON `string` or `object` types. +
_Items_: (for `string`) The item shall be a single _flag option_. +
_Items_: (for `object`) The item shall be a valid _structured option_. +
_Description_:
  A _structured options object_ can contain this field.

[#strctopt-names,reftext=strctopt.schema.names]
====== Names [.right]#[<<strctopt-strctopt-names>>]#

_name_: ::
  one or more of: +
  U+0061 .. U+007A LATIN SMALL LETTER A .. Z +
  U+0030 .. u+0039 DIGIT ZERO .. NINE +
  U+005F LOW LINE U+002D HYPHEN-MINUS
_scope_: ::
  _name_ _scope-designator_ _scope_~opt~
_scope-designator_: ::
  U+002E FULL STOP

The _name_ `std` is reserved for _flag options_ and _structured options_
defined in this standard.

Applications can specify vendor designated _name_ parts outside of this
standard.

[#strctopt-flag-opt,reftext=strctopt.schema.flag]
====== Flag Option [.right]#[<<strctopt-flag-opt>>]#

_flag-option_: ::
  one of: _yes-flag_ _no-flag_
_yes-flag_: ::
  one of: _yes-flag-name_ _scoped-yes-flag-name_
_yes-flag-name_: ::
  _name_
_scoped-yes-flag-name_: ::
  _scope_~opt~ _name_
_no-flag_: ::
  one of: _no-flag-name_ _scoped-no-flag-name_
_no-flag-name_: ::
  _no-flag-prefix_ _name_
_scoped-no-flag-name_: ::
  _scope_~opt~ _no-flag-name_
_no-flag-prefix_: ::
  U+006E LATIN SMALL LETTER N U+006F LATIN SMALL LETTER O +
  U+002D HYPHEN-MINUS

A _flag option_ is an option that allows or prevents the specified semantics
of the option.

A _flag option_ shall be either a _yes-flag_ or _no-flag_.

A _yes-flag_ allows the semantics in the application as specified by effects of
that behavior.

A _no-flag_ prevents the semantics in the application as specified by effects
of that behavior.

A flag option without a _scope_ shall be equivalent the same flag option with a
`std.` scope.

[#strctopt-struct-opt,reftext=strctopt.schema.struct]
====== Structured Option [.right]#[<<strctopt-struct-opt>>]#

A structured option JSON object shall contain a _structured-option-name_
field.

A structured option JSON object can contain additional fields as specified by
the option specification.

_Name_: `name` +
_Type_: `string` +
_Value_: A valid _structured-option-name_. +
_Description_: The name of the structured option.

_structured-option-name_: ::
  _scope_~opt~ _name_

A  structured option without a _scope_ shall be equivalent to the same
structured option with a `std.` _scope_.

[#strctopt-opt-opt,reftext=strctopt.schema.opt.opt]
====== Option `std.opt` [.right]#[<<strctopt-opt-opt>>]#

The `std.opt` option defines an option to refer to additional structured
options (<<strctopt>>) to process.

An application shall implement this option.

The `std.opt` option shall have the following fields.

_Name_: `name` +
_Type_: `string` +
_Value_: `std.opt` +
_Description_: The name of the option.

_Name_: `files` +
_Type_: `string` or `array` +
_Value_:
  (for `string`) A pathname to a file containing structured options
  (<<strctopt>>). +
_Value_:
  (for `array`) A list of pathname `string` items to files containing structured
  options (<<strctopt>>) +
_Description_:
  One or more references to files that include additional structured options
  (<<strctopt>>) that are processed as if they occur at the location of the
  `std.opt` option.

=== JSON Schema

Insert clause after _Annex A_.

[.ins.text-justify]
[#strctopt-json-schema,reftext=strctoptjschm]
==== Annex B (informative) Structured Options _JSON Schema_ [.right]#[<<strctopt-json-schema>>]#

[#strctopt-json-schema-general,reftext=strctoptjschm.general]
===== General [.right]#[<<strctopt-json-schema-general>>]#

This Annex defines the structured options capability schema
(<<strctopt-schema>>) in terms of a _JSON Schema_. A _JSON Schema_ refers to the
IETF RFC draft "JSON Schema: A Media Type for Describing JSON Documents" as
specified in https://json-schema.org/draft/2020-12/json-schema-core.html.

This JSON Schema can be referenced as the `$schema` field with URI value of
`"https://raw.githubusercontent.com/cplusplus/ecosystem-is/release/schema/std_opt-1.0.0.json"`.

[#strctopt-json-schema-spec,reftext=strctoptjschm.spec]
===== JSON Schema Specification [.right]#[<<strctopt-json-schema-spec>>]#

[source,json]
----
include::std_opt-1.0.0.json[]
----

== License

This work is licensed under the Creative Commons Attribution 4.0 International
License. To view a copy of this license, visit
http://creativecommons.org/licenses/by/4.0/ or send a letter to Creative
Commons, PO Box 1866, Mountain View, CA 94042, USA.
