= Tool Introspection
:copyright: Copyright 2022 René Ferdinand Rivera Morell
:email: grafikrobot@gmail.com
:authors: René Ferdinand Rivera Morell
:audience: SG15
:revdate: {docdate}
:version-label!:
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 10
:source-highlighter: rouge
:source-language: c++
:toc: left
:toclevels: 2
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:table-caption: Table 

++++
<style>
.sectionbody > div > .ins {
  border-left: solid 0.4em green;
  padding-left: 1em;
  text-decoration: underline solid green;
  text-underline-offset: 0.3em;
}
.def > .content :first-child {
  margin-left: 0;
}
.def > .content > * {
  margin-left: 3em;
}
.icon .title {
  font-size: 250%;
}
</style>
++++

Document number: :: ISO/IEC/JTC1/SC22/WG21/{revnumber}
Date: :: {revdate}
Audience: :: {audience}
Reply-to: ::
René Ferdinand Rivera Morell - _grafikrobot at gmail dot com_

== Abstract

We propose to add a mechanism for {CPP} tools to communicate what capabilities
a tool implements from the Ecosystem IS.
footnote:EcoIS[https://wg21.link/P2656 {CPP} Ecosystem International Standard]

== Revision History

=== Revision 2 (June 2023)

Change wording to match text in draft IS.

=== Revision 1 (May 2023)

Addition of scope, functionality levels, use cases, and wording.
Simplified introspection and declaration interfaces to make implementing
introspection trivial and declaration straightforward. The simplification
removes the _bounded_ introspection interface as superfluous.

=== Revision 0 (December 2022)

Initial text.

== Motivation

{CPP} tools will implement the aspects of the Ecosystem IS footnote:EcoIS[] that
are relevant to the particular tool. And when they implement those aspects they
may implement a particular edition of them. In order to allow other tools to
adjust their behavior to accommodate such differences we need a mechanism of
introspection for all tools. Additionally when one tool requests to use another
tool's Ecosystem IS aspect it's desirable to consistently communicate which
edition(s) of that aspect it can use.

== Scope

This proposal aims to specify a method for tools to communicate which specific
aspects of the Ecosystem IS they support and adhere to consumers (either other
tools or users). It does not prescribe which aspects of the Ecosystem IS the
tools must support or adhere to except to prescribe that supporting any
capability of the Ecosystem IS must also support this aspect. Ultimately it
wants to make it possible to address two cases:

* What does the tool support and adhere to?
* The tool should adhere to what the consumer asks if possible.

== Design

There are two aspects that this proposal covers:

Introspection:: A tool reporting its capabilities to a consumer.

Declaration:: A consumer specifying the capability edition and version.

_Introspection_ would allow a consumer to ask the target tool what versions of
of capabilities it supports. The target tool would respond with the range of
capabilities, or nothing, that it supports. With that information the consumer
can go ahead and follow the defined standard, in the Ecosystem IS
footnote:EcoIS[], to further interact with the target tool.

For _declaration_ a consumer can specify a particular capability and a version
to interact with. And if the target tool recognizes the specification it can
continue to process the consumer's use of that capability.

Even though these are two separate functions they are by necessity tied to each
other. In order for this pairing to work, and generally for tool
interoperability to work, the tool consumers and target tools must operate on
this minimal pair of functions to bootstrap their interactions. To make that
possible, this design follows some basic tenets:

[horizontal]

Minimal:: The interface of the target tool is a single universal command line
argument for each of the two operations.

Concise:: The information communicated to and from the target tool and consumer
is as brief as needed to convey the required information.

Robust:: The interface and information should not result in failure conditions
for either the consumer or target tool. Both ends of the interactions need to
rely on the stability of the interface to then be able to interoperate.

=== Introspection

NOTE: We used to include a _bounded_ introspection option. But turned out to be
not worth the added complexity in the consumer and tool.

The consumer can use a single method to query the target tool and obtain all the
capabilities that are available or specifically requested. The use case
supported is for unbounded _introspection_ of the available capabilities with a
single valueless `--std-info` option.

And unbounded introspection simply returns everything the tool is capable
of doing. The tool has the option to respond with either all minimal single
(aka bare) versions or full version ranges. Either can be trivially implemented
by tools as most time it can be a hard-wired response text.

Running a tool with the option would look like the following:

[source,shell]
----
$ tool --std-info
----

And could produce this as a minimal JSON output to indicate the single version
of the capabilities it supports:

[source,json]
----
{
  "$schema": "https://raw.githubusercontent.com/cplusplus/ecosystem-is/release/schema/std_info-1.0.0.json",
  "std:info": "1.0.0"
}
----

Or could produce this as a JSON output in the case of full version ranges:

[source,json]
----
{
  "$schema": "https://raw.githubusercontent.com/cplusplus/ecosystem-is/release/schema/std_info-1.0.0.json",
  "std:info": "[1,2.5]"
}
----

Which would minimally indicate that the tool only supports the introspection
capability at versions "1.0.0" through "2.5.0".

=== Declaration

The consumer can inform, i.e. declare, to the target tool that specific
capabilities should use particular versions when responding with information
using one or more `--std-info=<VersionSpec>` options. The declarations can only
exist in tandem with options for the mentioned capabilities. It's expected that
a consumer will first _introspect_ a target tool to discover what it supports.
Followed by the consumer _declaring_ to the target tool what version(s) of the
capabilities it is willing to consume. The target tool can then either accept
the declared capability versions or indicate an error.

An exchange between a consumer and target tool would begin with the
_introspection_:

[source,shell]
----
tool "--std-info"
----

With a target tool response:

[source,json]
----
{
  "$schema": "https://raw.githubusercontent.com/cplusplus/ecosystem-is/release/schema/std_info-1.0.0.json",
  "std:info": "[1,2)",
  "gcc:extra": "[2.1]"
}
----

Which the consumer can use to _declare_ the specific capability versions:

[source,shell]
----
tool "--std-decl=std:info=2.0.0" "--std-decl=gcc:extra=2.1.0" ...
----

=== Levels

For some use cases it helps to simplify the extent of information the
introspection understands. While it would be reasonable to expect a tool written
in a modern general purpose programming language to fully implement all aspects
of the introspection. It would not be practical to have a shell script parse
and recognize the more challenging aspect of parsing version number ranges and
matching them together. To support such use cases the introspection has to
support levels "min" and "full".

Obviously the "full" level equates to the tool understanding all the arguments
and values. The "min" level only understands these:

* Only introspection `--std-info` option.
* Single version number in the responses for `--std-info`.

This has the effect that a tool which only support the "min" level can only
support specific versions of the capabilities it implements. But it also means
that consumers will need to adjust their behavior to the tool instead of being
able to ask the tool to adjust to the consumer. Consequently the consumer will
likely have the more complex logic to do that adjustment.

=== Capabilities

For this proposal capabilities refers to any published coherent target tool
interface. This can include any single interface, like a single target tool
option. Or it can include a collective interface of the target tool that covers
many options. A capability is specified as a series of "scoped" identifiers
separated by colons (":"). The capability must match this regular expression:
footnote:Regex[ECMAScript® 2022 language specification, 13th edition, June 2022 (https://www.ecma-international.org/publications-and-standards/standards/ecma-262/)]

[source,plan_text]
----
^[a-z_]+(:[a-z_]+)+$
----

At minimum a capability has two components. The first component is a general
scope that identifies if the capability is one in the IS, or if it's a tool
vendor capability.

Standard:: A capability with a scope of `std` indicates that it's defined in the
IS. footnote:EcoIS[]

Vendor:: Any other capability, i.e. other than `std`, is available for vendors
to use as extensions outside the IS. footnote:EcoIS[]

=== Version Specification

When indicating the version, or versions, to the target tool or the consumer the
version information is specified in two possible forms: a single version, or a
single version range.

==== Single Version

A single version in this proposal is composed of a one to three dotted whole
numbers. The numbers are expected to be strictly increasing. But otherwise do
not impart any meaning to the components. Specifically this does not impart any
form of semantic meaning between versions. Although the specification of the
capabilities themselves may define such a semantic meaning. The format for the
version must match the regular expression:
footnote:Regex[]

[source,plain_text]
----
^[0-9]+([.][0-9]+){0,2}$
----

==== Version Range

A version range in this proposal indicates a lower and upper bound of versions.
It is composed of a pair of versions, separated by a comma, and bracketed by
either an inclusive or exclusive symbol. This matches the intuition of a
mathematic interval, but with the use of the version triplet number line.
footnote:[Wikipedia: Interval (mathematics) (https://en.wikipedia.org/wiki/Interval_(mathematics))]
Like the interval notation the `()` brackets indicate an exclusive point. And
the `[]` brackets indicate an inclusive point. As versions are decidedly not
single integers we use a `,` (comma) to separate the start and end of the range
instead of using `..`. Hence the format for the version range must match the
regular expression:
footnote:Regex[]

[source,plain_text]
----
^[[(][0-9]+([.][0-9]+){0,2},[0-9]+([.][0-9]+){0,2}[)\\]]$
----

=== Version Matching

When given two version specifications tools will need to match the two to
determine the sub-range that are compatible with both. There are two aspects to
doing that matching: comparing the two single versions, and evaluating the
sub-range interval.

==== Single Version Comparison

Comparing two single versions equates to three-way comparing each of the
components of both, `a` and `b`, as:

. If the whole numbers of the first components, `i` and `j`, are not equal the
comparison is either `a < b` or `a > b` if `i < j` or `i > j` respectively.
Otherwise,
. If the whole numbers of the second components, `k` and `l`, are not equal the
comparison is either `a < b` or `a > b` if `k < l` or `k > l` respectively.
Otherwise,
. If the whole numbers of the third components, `m` and `n`, are not equal the
comparison is either `a < b` or `a > b` if `m < n` or `m > n` respectively.
Otherwise,
. The versions are equal, i.e. `a == b`.

==== Range Comparison

Tools will need to compare either a single version to a version range, or a
version range to another range to determine the overlapping version sub-range.
The single version to a version range comparison can be reformulated to a
range-to-range comparison. I.e. a comparison of a single range `a` to a range
`b` is equivalent to a comparison of range `[a,a]` to range `b`. Hence we only
need to consider the range-to-range comparison. Although implementations may
use special case for comparing single-to-range and range-to-single.
Range-to-range should follow something like the following to compare a range
`a,b` to `m,n`, with some varied inclusive or exclusive ends:

. If `b < m` or `n < a` the range is _empty_.
. Otherwise, assign a _partial_ range `x,y = max(a,m), min(b,n)`.
. If `a` or `m` are inclusive, then:
.. If `b` or `n` are inclusive, then the range is `[x,y]`.
.. Otherwise, the range is `[x,y)`.
. Otherwise, if `b` or `n` are inclusive, then the range is `(x,y]`.
. Otherwise, the range is `(x,y)`.

=== Format

The information reported by _introspection_ is a JSON
footnote:json[ISO/IEC 21778:2017 Information technology — The JSON data interchange syntax, (https://www.iso.org/standard/71616.html)]
format document. Some advantages to using JSON:

* It is widely used and available either natively or through libraries in many
programming languages. Which is particularly important as {CPP} tools are
written in an array of differing programming languages.
* It is a simple format to understand by both programs and humans.

In maintaining our goals of the interface being minimal, concise, and robust,
the format for communicating the capabilities is a single key/value collection,
i.e. a JSON object.
footnote:json[]

Capability Identifier:: The _key_ is a string with the capability identifier. The
format of the is as described in the <<Capabilities>> section.

Version Specification:: The _value_ indicates the versions supported by the tool
for the capability. The versions follows the format described in the
<<Version Specification>> section.

In addition to the _capability identifier_ / _version specification_ members,
there are additional special members:

Schema:: The document can also specify a reference to a JSON Schema.
footnote:jschema[JSON Schema: A Media Type for Describing JSON Documents (http://json-schema.org/latest/json-schema-core.html)]
For this the _key_ would be `$schema`, and the _value_ would a URI to a
published stable schema
(`https://raw.githubusercontent.com/cplusplus/ecosystem-is/release/schema/std_info-1.0.0.json`).

There is one designated capability that is required to appear in the document:
The `std:info` capability with a corresponding _version specification_. This
requirement allows a consumer to identify the format of the rest of the document
at all times.

This is a minimal conforming document:

[source,json]
----
{
  "std:info": "1.0.0"
}
----

This is also a minimal conforming document. But specifies a range of versions
supported for the `std:info` capability:

[source,json]
----
{
  "std:info": "[1.0.0,2.0.0)"
}
----

This example adds a custom vendor capability and the schema reference:

[source,json]
----
{
  "$schema": "https://raw.githubusercontent.com/cplusplus/ecosystem-is/release/schema/std_info-1.0.0.json",
  "std:info": "[1.0.0,2.0.0)",
  "gcc:extra": "1.5.0"
}
----

See the <<Wording>> for a <<JSON Schema>> for this format.

=== Capability Versions

The capabilities and their version is expected to work similar to how {CPP}
feature macro version ([version.syn]) in that it specifies if a feature of a
standard is implemented and at what version. Although the meaning of the
capability version is not defined, it's recommended that it follow some simple
rules:

* The _major-number_ should only change for large changes.
* The _minor-number_ should only change for fixes that are significant, but not
  large.
* The _patch-number_ should only change for fixes that are simple and small.

That is, it should roughly follow the industry understanding of sematic
versioning.
footnote:Semver[Semantic Versioning (https://semver.org/)]

* Each part of the version number should always increment, but;
* The _minor-number_ should reset to zero when the _major-number_ increases,
  equivalently for the _patch-number_ and _minor-number_.

These rules set it apart from the {CPP} feature macros that they impart some
meaning to a version relative to other versions.

=== Impact On The Standard

This specification adds new functionality that is partly required for programs.
Other specifications that define program behavior will need to follow this
specification for conformance to the Ecosystem IS.

== Implementation Experience

None yet.

== Polls

=== SG15: P2717R0 (2023-01-27)

SG15 wants to pursue defining in the Tooling IS a way for tools to provide
portable information about which parts of the Tooling IS and vendor extensions
they support.

[options="header,autowidth",cols="^0,^0,^0,^0,^0"]
|===
| SF | F | N | A | SA
| 5  | 3 | 0 | 0 | 0
|===

== Wording

Wording is relative to
link:https://github.com/cplusplus/ecosystem-is/tree/86cfbd72b9fae73554935d5f7039a798b5583628[ecosystem-is/86cfbd7].
footnote:[Working Draft, {CPP} Ecosystem International Standard 2023-04-01 (https://github.com/cplusplus/ecosystem-is/tree/86cfbd72b9fae73554935d5f7039a798b5583628)]

=== Normative references

In [intro.refs] add:

[.ins.text-justify]
JSON::
ISO/IEC 21778:2017, _Information technology — The JSON data interchange syntax_
POSIX::
ISO/IEC 9945:2009, _Information technology — Portable Operating System Interface (POSIX®) Base Specifications, Issue 7_

=== Specification: Conformance

Insert clause before _Terms and definitions_ [intro.defs].

[.ins.text-justify]
[#cnf,reftext=cnf]
==== Conformance [.right]#[<<cnf>>]#

A conforming implementation shall meet the following criteria for conformance to
this standard:

— An application shall support the _minimum level_ functionality of
introspection (<<intspct-min>>).

=== Definitions

Add the following to _Terms and definitions_ [intro.defs].

[.ins.text-justify]
[#defns-application,reftext=defns.application]
==== application [.right]#[<<defns-application>>]#

a computer program that performs some desired function.

+[+ _Note 1_: From POSIX. -- _end note_ +]+

[.ins.text-justify]
[#defns-capability,reftext=defns.capability]
==== capability [.right]#[<<defns-capability>>]#

an aspect of an overall specification that defines a subset of the entire
specification.

[.ins.text-justify]
[#defns-file,reftext=defns.file]
==== file [.right]#[<<defns-file>>]#

an object that can be written to, or read from, or both.

+[+ _Note 1_: From POSIX. -- _end note_ +]+

=== Specification: Introspection

Insert clause after _Terms and definitions_ [intro.defs].

[.ins.text-justify]
[#intspct,reftext=intspct]
==== Introspection [.right]#[<<intspct>>]#

[#intspct-pre,reftext=intspct.pre]
===== Preamble [.right]#[<<intspct-pre>>]#

This clause describes options, output, and formats that describe what
capabilities of this standard an application supports. An application shall
support the _minimum level_ functionality (<<intspct-min>>). An application can
support the _full level_ functionality (<<intspct-full>>).

This clause specifies the `std:info` capability (<<intspct-cap>>).

[#intspct-overview,reftext=intspct.overview]
===== Overview [.right]#[<<intspct-overview>>]#

--
`_application_ [--std-info[=_declaration_]] [--std-info-out=_file_]`
--

[#intspct-options,reftext=intspct.options]
===== Options [.right]#[<<intspct-options>>]#

[#intspct-opt-info,reftext=intspct.opt.info]
===== Information Option [.right]#[<<intspct-opt-info>>]#

This option shall be supported.

`--std-info`::
Outputs the version information of the capabilities supported by the
application.
The option can be specified zero or one time.
The application shall support the option for _minimum level_ (<<intspct-min>>)
functionality.

[#intspct-opt-out,reftext=intspct.opt.out]
===== Information Output Option [.right]#[<<intspct-opt-out>>]#

This option shall be supported.

`--std-info-out=_file_`::
The pathname of a file to output the information to. If _file_ is '`-`', the
standard output shall be used.
The application shall support the option for _minimum level_ (<<intspct-min>>)
functionality.
Not specifying this option while specifying the `--std-info` option
(<<intspct-opt-info>>) shall be equivalent to also specifying a
`--std-info-out=-` option.

[#intspct-opt-decl,reftext=intspct.opt.decl]
===== Declaration Option [.right]#[<<intspct-opt-decl>>]#

This option should be supported.

`--std-info=_declaration_`::
Declares the required capability version of the application.
The option can be specified any number of times.
The application shall support the option for _full level_ (<<intspct-full>>)
functionality.

[#intspct-output,reftext=intspct.output]
===== Output [.right]#[<<intspct-output>>]#

An application shall output a valid JSON text file that conforms to the
introspection schema (<<intspct-schema>>) to the file specified in the options
(<<intspct-opt-out>>).

[#intspct-schema,reftext=intspct.schema]
===== Schema [.right]#[<<intspct-schema>>]#

An introspection JSON text file shall contain one introspection JSON object
(<<intspct-schema-obj>>).

[#intspct-schema-obj,reftext=intspct.schema.obj]
====== Introspection Object [.right]#[<<intspct-schema-obj>>]#

The _introspection object_ is the root JSON object of the introspection JSON
text.

An _introspection object_ can have the following fields.

[#intspct-fld-schema,reftext=intspct.schema.schema]
====== JSON Schema Field [.right]#[<<intspct-fld-schema>>]#

_Name_: `$schema` +
_Type_: `string` +
_Value_:
  The value shall be a reference to a JSON Schema specification. +
_Description_:
  An _introspection object_ can contain this field.
  If an _introspection object_ does not contain this field the value shall be a
  reference to the JSON Schema corresponding to the current edition of this
  standard.

[#intspct-fld-cap,reftext=intspct.schema.cap]
====== Capability Field [.right]#[<<intspct-fld-cap>>]#

_Name_: _capability-identifier_ (<<intspct-cap>>) +
_Type_: `string` +
_Value_:
  The value shall be a _version-number_ for _minimum level_ functionality.
  Or the value shall be a _version-range_ for _full level_ functionality. +
_Description_:
  An _introspection object_ can contain this field one or more times.
  When the field appears more than one time the name of the fields shall be
  unique within the _introspection object_.

[#intspct-cap,reftext=intspct.cap]
===== Capabilities [.right]#[<<intspct-cap>>]#

_capability-identifier_: ::
  _name_ _scope-designator_ _name_ _sub-capability-identifier~opt~_
_sub-capability-identifier_: ::
  _scope-designator_ _name_ _sub-capability-identifier~opt~_
_name_: ::
  one or more of: +
  `a b c d e f g h i j k l m` +
  `n o p q r s t u v w x y z` +
  `_`
_scope-designator_: ::
  `:`

A _capability-identifier_ is composed of two or more _scope-designator_
delimited _name_ parts.

The _name_ `std` in a _capability-identifier_ is reserved for capabilities
defined in this standard.

Applications can specify vendor designated _name_ parts defined outside of this
standard.

[#intspct-vers,reftext=intspct.vers]
===== Versions [.right]#[<<intspct-vers>>]#

A version shall be either a single version number (<<intspct-vers-num>>) or a
version range (<<intspct-vers-range>>).

A single version number shall be equivalent to the inclusive version range
spanning solely that single version number.

+[+ _Note 1_:
That is the version number `i.j.k` is equivalent to version range
`[i.j.k,i.j.k]`.
— _end note_ +]+

[#intspct-vers-num,reftext=intspct.vers.num]
====== Version Number [.right]#[<<intspct-vers-num>>]#

_version-number_: ::
  _major-number_ _minor-patch-part~opt~_
_minor_patch_part_: ::
  `.` _minor-number_  _patch-part~opt~_
_patch-part_: ::
  `.` _patch-number_
_major-number_: ::
  _digits_
_minor-number_: ::
  _digits_
_patch-number_: ::
  _digits_
_digits_: ::
  one or more of: +
  `0 1 2 3 4 5 6 7 8 9`

A version number is composed of 1, 2, or 3 decimal numbers (_digits_)
separated by a period (`.`).

A version number composed of 1 decimal number is equivalent to that decimal
number followed by `.0.0`.

+[+ _Note 1_:
That is the version number `N` is equivalent to `N.0.0`.
— _end note_ +]+

A version number composed of 2 decimal number parts is equivalent to those
decimal number parts followed by `.0`.

+[+ _Note 2_:
That is the version number `N.M` is equivalent to `N.M.0`.
— _end note_ +]+

Version numbers define a total ordering where version number _a_ with parts
_i_, _j_, _k_ is ordered before version number _b_ with parts _p_, _q_, _r_
when: _i_ < _p_, or _i_ == _p_ and _j_ < _q_, or _i_ == _p_ and _j_ == _q_
and _k_ < _r_.

Otherwise version number _a_ is ordered before version number _b_ when:
_i_ > _p_, or _i_ == _p_ and _j_ > _q_, or _i_ == _p_ and _j_ == _q_
and _k_ > _r_.

Otherwise version number _a_ is the same as version number _b_.

[#intspct-vers-range,reftext=intspct.vers.range]
====== Version Range [.right]#[<<intspct-vers-range>>]#

_version-range_: ::
  _version-range-min-bracket_
  _version-min-number_ _version-range-max-part_~opt~
_version-range-max-part_: ::
  `,` _version-max-number_ _version-range-max-bracket_
_version-min-number_: ::
  _version-number_
_version-max-number_: ::
  _version-number_
_version-range-min-bracket_: one of ::
  `[ (`
_version-range-max-bracket_: one of ::
  `) ]`

A version range is composed of either one version number bracketed,
or two version numbers separated by a comma (`,`) and bracketed.

+[+ _Example 1_:
A version range with a single version number "`[1.0.0]`".
— _end example_ +]+

+[+ _Example 2_:
A version range with a two version numbers "`[1.0.0,2.0.0]`".
— _end example_ +]+

A version range _a_ that is `[_i_,_j_]` makes _i_ and _j_ inclusive version
range numbers.

A version range _a_ that is `(_i_,_j_)` makes _i_ and _j_ exclusive version
range numbers.

A version range _a_ that is `(_i_,_j_]` makes _i_ an exclusive version number.

A version range _a_ that is `[_i_,_j_)` makes _j_ an exclusive version number.

A version range with a single inclusive version number _x_ is equivalent to the
version range `[_x_,_x_]`.

A version range with a single exclusive version number _x_ is invalid.

An exclusive version number _x_ does not include the version number _x_ when
compared to another version number _y_.

A version range _a_ with version numbers _i_ and _j_ when compared to a version
range _b_ with version number _m_ and _n_ will result in an empty version range
when: _j_ < _m_ or _n_ < _i_.f

Otherwise if _i_ or _m_ are inclusive version numbers and if _j_ or _n_ are
inclusive version numbers the resulting range when _a_ is compare to _b_ is
the inclusive version numbers "lesser of _i_ and _m_" and
"lesser of _j_ and _n_".

Otherwise if _i_ or _m_ are inclusive version numbers and if _j_ or _n_ are
inclusive version numbers the resulting range when _a_ is compare to _b_ is
the inclusive version number "lesser of _i_ and _m_" and the exclusive version
number "lesser of _j_ and _n_".

Otherwise if _j_ or _n_ are inclusive version numbers the resulting range when
_a_ is compared to _b_ is the exclusive version number "lesser of _i_ and _m_"
and the inclusive version number "lesser of _j_ and _n_".

Otherwise the resulting range when _a_ is compared to _b_ is the exclusive
version numbers "lesser of _i_ and _m_" and "lesser of _j_ and _n_".

[#intspct-min,reftext=intspct.min]
===== Minimum Level [.right]#[<<intspct-min>>]#

An application that supports the _minimum level_ functionality indicates it by
specifying a single version (<<intspct-vers-single>>) as the value of the
`std:info` capability (<<intspct-cap>>).

+[+ _Example 1_: +
`{ "std:info": "1.0.0" }` +
— _end example_ +]+

[#intspct-full,reftext=intspct.full]
===== Full Level [.right]#[<<intspct-full>>]#

An application can support the _full level_ functionality as defined in this
section. An application that reports supporting the _full level_ functionality
shall support all of the functionality in this section.

An application that supports the _full level_ functionality indicates it by
specifying a version range (<<intspct-vers-single>>) as the value of the
`std:info` capability (<<intspct-cap>>).

+[+ _Example 1_: +
`{ "std:info": "[1.0.0]" }` +
— _end example_ +]+

[#intspct-info,reftext=intspct.info]
===== Introspection Information [.right]#[<<intspct-info>>]#

An application shall output an introspection schema (<<intspct-schema>>) that
contains one capability field for each capability that the application supports
when given the `--std-info` option (<<intspct-opt-info>>).

An application shall indicate the single version (<<intspct-vers-num>>) or
version range (<<intspct-vers-range>>) of each capability it supports as the
value of the capability field.

[#intspct-dcl,reftext=intspct.dcl]
===== Introspection Declaration [.right]#[<<intspct-dcl>>]#

An application that supports the _full level_ functionality when given one or
more `--std-info=_declaration_` options shall conform its functionality to the
indicated edition of this standard in the given _declaration_ _version-number_
for the given capability.

_declaration_: ::
  _capability-identifier_ `=` _version-number_

An application, when not given a `--std-info=_declaration_` option for a
capability it supports, should conform its functionality to the most recent
version of the standard it supports for that capability.

An application, when given a capability declaration option and the given
version is outside of the version range that the application supports, should
indicate an error.

=== JSON Schema

Insert clause before _Bibliography_.

[.ins.text-justify]
[#intspct-json-schema,reftext=intsjschm]
==== Annex A (informative) Tool Introspection _JSON Schema_ [.right]#[<<intspct-json-schema>>]#

[#intspct-json-schema-general,reftext=intsjschm.general]
===== General [.right]#[<<intspct-json-schema-general>>]#

This Annex describe defines the introspection capability schema
(<<intspct-schema>>) in terms of a _JSON Schema_. A _JSON Schema_ refers to the
IETF RFC draft "JSON Schema: A Media Type for Describing JSON Documents" as
specified in https://json-schema.org/draft/2020-12/json-schema-core.html.

This JSON Schema can be referenced as the `$schema` field with URI value of
`"https://raw.githubusercontent.com/cplusplus/ecosystem-is/release/schema/std_info-1.0.0.json"`.

[#intspct-json-schema-spec,reftext=intsjschm.spec]
===== JSON Schema Specification [.right]#[<<intspct-json-schema-spec>>]#

[source,json]
----
include::std_info-1.0.0.json[]
----

== Examples

=== Portable Command Lines

Assuming that the Ecosystem IS specifies a common set of portable command line
compiler options an interaction between a build system (or user at a command
prompt) and a compiler could look like:

Build systems asks the compiler for supported capabilities:

[,shell]
----
$ c++ --std-info
{ "std:info": "[1]", "std:cli:c++", "[1]" }
----

NOTE: The build system would likely want to cache that information as it's
likely to be static for the release of the compiler.

The build system could then declare and use any such portable compiler options:

[,shell]
----
$ c++ --std-info=std:cli:c++=1 -std=c++26 -I /home/user/boost -o myapp main.cpp
----

The interaction when the compiler tool only supports the minimum level would be:

[,shell]
----
$ c++ --std-info
{ "std:info": "1", "std:cli:c++", "1" }
$ c++ -std=c++26 -I /home/user/boost -o myapp main.cpp
----

This example predicts that it might be useful outside of the {CPP} ecosystem by
using `std:cli:c++` to indicate a {CPP} specific command line. It could be
that Fortran uses a different, but possibly overlapping CLI:

[,shell]
----
$ gcc --std-info
{ "std:info": "1", "std:cli:c++", "1", "gcc:cli:fortran", "1" }
$ gcc -std=f2018 -o myapp main.fpp
----
