[.ins.text-justify]
[#strctopt-core,reftext=strctopt.core]
= Structured Core Options [.right]#[<<strctopt-core>>]#
:texroot: ecosystem.tex

[#strctopt-core-pre,reftext=strctopt.core.pre]
== Preamble [.right]#[<<strctopt-core-pre>>]#

This clause describes the schema and semantics of core structured options
[.iref]#([strctopt.schema.struct])# for {CPP} compiler front-ends.

This clause specifies the `std.strctopt.core` capability [.iref]#([intspct.cap])#
vresion `1.0.0`.

An application can implement this capability.

An application that implements the `std.strctopt.core` capability shall include
the `std.strctopt.core` field and version value in the introspection JSON
text output [.iref]#([intspct.schema.cap])#.

[.ins.text-justify]
[#strctopt-core-inc,reftext=strctopt.core.inc]
== Include Directories [.right]#[<<strctopt-core-inc>>]#

The `std.include` option defines an option to specify a list of directory
pathnames that a {CPP} preprocessor uses to search for inclusion.

The `std.include` option shall have the following fields.

[.itemdescr]
[.fldname]#_Name_:# `name` +
[.fldtype]#_Type_:# `string` +
[.fldval]#_Value_:# `std.include` +
[.flddesc]#_Description_:# The name of the option.

[.itemdescr]
[.fldname]#_Name_:# `files` +
[.fldtype]#_Type_:# `string` or `array` +
[.fldval]#_Value_:#
  (for `string`) A pathname to a directory. +
[.fldval]#_Value_:#
  (for `array`) A list of pathname `string` items to directories. +
[.flddesc]#_Description_:#
  One or more entries to directories that are appended in the order given to
  the list of directories searched by the header inclusion of a {CPP}
  preprocessor.

[.ins.text-justify]
[#strctopt-core-xxx,reftext=strctopt.core.xxx]
== Xxx [.right]#[<<strctopt-core-xxx>>]#
