= C++ Ecosystem International Standard
:copyright: Copyright 2022 René Ferdinand Rivera Morell
:email: grafikrobot@gmail.com
:authors: René Ferdinand Rivera Morell, et al.
:audience: SG15
:revdate: {docdate}
:version-label!:
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 5
:source-highlighter: rouge
:source-language: c++
:toc: left
:toclevels: 2
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:table-caption: Table 

++++
<style>
.sectionbody > div > .ins {
  border-left: solid 0.4em green;
  padding-left: 1em;
  text-decoration: underline solid green;
  text-underline-offset: 0.3em;
}
.def > .content :first-child {
  margin-left: 0;
}
.def > .content > * {
  margin-left: 3em;
}
.icon .title {
  font-size: 250%;
}
.imageblock svg {
  width: 100% !important;
}
</style>
++++

Document number: :: ISO/IEC/JTC1/SC22/WG21/{revnumber}
Date: :: {revdate}
Audience: :: {audience}
Reply-to: ::
René Ferdinand Rivera Morell - _grafikrobot at gmail dot com_ - B2 Maintainer +
Ben Craig - _ben dot craig at gmail dot com_

== Abstract

We propose to publish an International Standard that specifies formats,
processes, definitions, and so on, that facilitates the interoperation of the
tools and systems that implement, and interface with, the {CPP} International
Standard (ISO/IEC 14882).

== Revision History

=== Revision 1 (January 2023)

Adds proposed timeline and process for development of the IS from the first
edition onwards. Also adds "2717 Tool Introspection" as a goal for the first
edition.

Include record of polls.

=== Revision 0 (October 2022)

Initial text.

== Motivation

Interoperability is a challenge in today's {CPP} ecosystem. At a time when the
{CPP} language is advancing, the community is struggling to manage the
challenges of the complexity and variability of the tools, technologies, and
systems that make {CPP} possible. In the view of users the {CPP} ecosystem is
fractured in ways that hinder its successful advancement.

The continued success of {CPP} is tied not solely to the language, but to the
{CPP} ecosystem. The interoperability within that ecosystem is key to
surmounting the challenges of further growth of the language for the benefit of
users. It is therefore critical that we expand the specifications that WG21
produces to bring coherence to the {CPP} ecosystem.

Users should be able to mix and match their preferred build systems, compilers,
linkers, package managers, static analyzers, runtime analyzers, debuggers,
profilers, etc. without needing the tools to have vendor specific knowledge of
each other. Vendors should be able to focus on direct tool improvements, rather
than figuring out how to interact with yet another proprietary interface.

== Scope

This new standard aims to clarify practice in a common
way. It can contain various aspects of the {CPP} Ecosystem:

. _Definitions_ :
We will need a common language to refer to the many components
and aspects of the ecosystem. With a shared understanding of components like:
compilers, linkers, analyzers, debuggers, package managers, preprocessors,
source files, object files, library files, shared library files, executables, 
and more, we can subsequently formulate specifications for them.

. _Format Specifications_ :
The tools that make up the ecosystem work by consuming and producing a variety
of data in a variety of formats. We will need to specify those formats such that
the tools and components can operate effectively.

. _Operation Specifications_ :
It's not enough to know what the information the ecosystem contains, we
also need to specify how that data is consumed and produced to aid in
inter-operation of the variety of use cases in the {CPP} ecosystem.

This new standard will not:

. _Mandate any single vendor tools_ :
It is not a goal to seek single "blessed" tools in the ecosystem. We have a
wide variety of good tools in the ecosystem. And we look forward to those tools
cooperating with each other.

. _Prohibit vendor extensions_ :
It is not a goal to prevent vendor innovation in what the ecosystem tools can
achieve. As such we welcome extensions and look towards the advancement that
such extensions bring.

. _Modify the {CPP} Language Standard_ :
It is not a goal to alter, in any way, the {CPP} Language Standard. It is
important that how we define the tools of the {CPP} ecosystem evolves
independent of the language.

== Goals

Like the {CPP} Language Standard this one will never be complete or finished.
And it will take time and effort to provide coverage of the specifications
needed to put together a good basic picture of the ecosystem. While the scope
above defines an ideal completion, the goals for a first edition of this
standard could include some modest items:

. Definitions
. Format Specifications :
.. Build System <==> Package Manager Interoperation
.. File Names
.. Introspection

=== Definitions

We will need some basic definitions as needed to circumscribe the specifications
included in this first standard.

=== Build System <==> Package Manager Interoperation

Specification of formats and operation of interoperability between build
systems and package managers. Current and previous work on this:

* P2673 Common Description Format for {CPP} Libraries and Packages
footnote:[Common Description Format for {CPP} Libraries and Packages (https://wg21.link/p2673r0)]
* The CppCon 2022 presentation "The Case For a Standardized Package Description
Format",
footnote:[CppCon 2022: The Case For a Standardized Package Description Format, _Luis Caro Campos_ (https://cppcon.digital-medium.co.uk/session/2022/the-case-for-a-standardized-package-description-format/)]
prompted ongoing work to specify standard communication format between package
managers and build systems.
* P2577 {CPP} Modules Discovery in Prebuilt Library Releases
footnote:P2577[{CPP} Modules Discovery in Prebuilt Library Releases, _Daniel Ruoso_ (https://github.com/cplusplus/papers/issues/1232)]
* P2536 Distributing {CPP} Module Libraries with dependencies json files.
footnote:P2536[Distributing {CPP} Module Libraries with dependencies json files. _Olga Arkhipova_ (https://github.com/cplusplus/papers/issues/1199)]
* P2473 Distributing {CPP} Module Libraries.
footnote:P2473[Distributing {CPP} Module Libraries. _Daniel Ruoso_ (https://github.com/cplusplus/papers/issues/1131)]
* P1767 Packaging {CPP} Modules.
footnote:P1767[Packaging {CPP} Modules. _Richard Smith_ (https://github.com/cplusplus/papers/issues/522)]
* `libman`, A Dependency Manager ➔ Build System Bridge
footnote:libman[`libman`, A Dependency Manager ➔ Build System Bridge _Colby Pike_ (https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/libman/develop/data/spec.bs)]
* P1313 Let's Talk About Package Specification.
footnote:P1313[Let's Talk About Package Specification. _Matthew Woehlke_ (https://wg21.link/p1313)]
* P1177 Package Ecosystem Plan.
footnote:P1177[Package Ecosystem Plan. _René Ferdinand Rivera Morell_ (https://github.com/cplusplus/papers/issues/48)]

=== File Names

Specification of a minimal set of file names understood, and for what they
are understood, by the various tools in the ecosystem. Current and previous
work on this:

* P1838 Modules User-Facing Lexicon and File Extensions.
footnote:[Modules User-Facing Lexicon and File Extensions. _Bryce Adelstein Lelbach_, _Boris Kolpackov_ (https://github.com/cplusplus/papers/issues/727)]
* P1177 Package Ecosystem Plan.
footnote:P1177[]

=== Introspection

Specification of format and command options to provide implementation
information of the IS.

* D2717 Tool Introspection
footnote:[Tool Introspection. _René Ferdinand Rivera Morell_ (https://wg21.link/D2717R0)]

== Timeline

We believe that improving the interoperability in the {CPP} ecosystem is an
urgent problem to solve.

* We can't solve all the challenges of the ecosystem interoperation at once;
there are just too many of them.
* We need solutions sooner to show that vendors can count on a stable future
for them to build their tools on.
* We need implementations sooner to show users the value of the IS.
* We recognize that the IS will have errors that need to be addressed quickly.

Hence we aim to publish a standard quickly and provide updates to it as quickly.
The goal is to publish this new IS on a two (2) year cycle starting in 2023.
This means publishing the first edition in 2025. Subsequent versions would then
publish in 2027, 2029, and so on. Because we plan on a small initial standard
document we will follow the 24 month standards development track (SDT 24).
footnote:sdt24[Standards Development Track, 24 Months:
ISO/IEC Directives, Part 1 —
Consolidated ISO Supplement —
Procedure for the technical work
— Procedures specific to ISO _Section 2.1.6.1 General_
(https://isotc.iso.org/livelink/livelink?func=ll&objId=4230452&objAction=browse&sort=subtype)]

The timeline that follows lists milestones for relevant WG21 meetings.

=== 2023.1: Plan

Goal:: Finalize the plan for the development of the IS.

With the intent of keeping the first edition of the IS limited we expect to have
a rough idea of what will go into the IS by this time. SG15 will poll the plan
at this, or earlier, point. From this point we will have one year (12 months)
to hone proposals to merge into the IS.

=== 2023.2: Pre-Draft

Goal:: Approve skeleton draft of the IS.

We will have a minimal skeleton draft of the IS prepared. This draft will have
one or more papers merged into it, and will have outlines for the rest of the
content, as possible. We will ask EWG approval on this content to checkpoint
the work so far and the work going forward.

=== 2024.1: Proposal

Goal:: Submit formal proposal to create work item for the publication of
the new IS.

The proposal will include an initial, mostly complete, draft of the
intended content of the IS. Submitting at this meeting allows following the
SDT 24 track of development foornote:sdt24[] with a target publication in
Q3 2025. The goal being to avoid the rush of the preparations for the {CPP} 26
IS. As the work will be completed by Q1 2025.

NOTE: Provide for an 8 week ballot period on proposal acceptance.

=== 2024.3: Committee Draft (CD) Finalized

Goal:: Approve Committee Draft for National Body comments.

From submitting an initial draft in 2024.1 we will have completed incorporating
any detail changes that the draft text will be ready to get voted on. This will
mark, approximately, 1.5 years since the beginning of work on the new IS. The
goal at this WG21 meeting will be to address any urgent issues that could
prevent NB balloting of the IS draft.

NOTE: Provide for an 8 week ballot period on proposal acceptance.
And 2 (4?) weeks of comment compilation time.

=== 2025.1: Draft International Standard (DIS) Finalized

Goal:: Resolve collected NB comments and approve the final draft of the IS.

Consider and resolve NB comments compiled during the CD polling. With the first
IS on its way to publishing approval we can start discussions on what the
process and content will be going forward.

=== 2025.2: Future

Goal:: Formally begin on the next IS edition for 2027 by finalizing the ongoing
development plans.

From here we can start the ongoing two (2) year cycles of releasing updates to
the IS. In comparison to the C++ IS that would look like:

image::timeline.drawio.svg[opts=inline]

== Process

We expect the development of the IS to use two processes that mesh into the
existing processes of WG21:

Bootstrap::
Initial development and review in Tooling Study Group (SG15), followed by
review and approvals in Evolution Working Group (EWG) or Library Evolution
Working Group (LEWG). And from there continuing to the regular review and
approval of wording process.

Parallel::
Development and review can originate in any existing study group depending as
appropriate. Followed for review and approval by a new Tooling Working Group
(TWG). TWG would include consideration of wording of the IS itself. And, hence,
produce polls for WG21 plenary votes.

=== Bootstrap

We would use the _Bootstrap_ process for the first edition of the IS. Following
this process for the first edition has some advantages:

* It's a process we know. Which means it reduces initial overhead.
* The reduced overhead allows us to concentrate more time on the IS development
  itself.
* Gives us time to recruit people for the subsequent editions of the IS.
* Contributors build up knowledge on the process to prepare for the next
  IS edition.

But it has some drawbacks:

* It places higher burden on time for the EWG and Core groups to review the
  work.
* The EWG and Core groups usual experts might not all be familiar with the
  tooling and ecosystem domain.

Those are significant drawbacks although we think are ameliorated by: First,
scheduling the IS to complete a full year before the {CPP}26 time frame. And,
second, limiting the scope of the IS early in the time line resulting in more
time spent in SG15 on draft wording details.

=== Parallel

After the first edition of the IS we would switch to the _Parallel_ process.
Visually this process would alter the regular flow of WG21 in minor ways
resulting in:

image::process.drawio.svg[opts=inline]

Here the drawbacks from the _Bootstrap_ process are addressed. And we maintain
the advantages as we will have people ready and able to develop and process
further editions of the IS.

This process structure will, clearly, change over time as the IS grows and
experts fill similar roles to what we now have in WG21. Hence we expect to
eventually need a wording group and narrower domain specific study groups.

NOTE: SG15 would cease to operate. As TWG would assume the same
responsibilities.

== Polls

=== SG15: P2656R0 (2022-11-09)

SG15 recommends to WG21 to create a new Tooling IS with the scope and goals
described in P2656R0 when an approved working document has been produced.

[options="header,autowidth",cols="^0,^0,^0,^0,^0"]
|===
| SF | F | N | A | SA
| 13 | 3 | 4 | 0 | 0
|===

*Result*: pretty strong consensus

*Author*: SF

*Attendance*: 20 

=== EWG: P2656R0 (2022-11-10)

EWG is in favor of further work in the direction of starting an additional IS
for Tooling Interaction as proposed by P2656, and would like to see this again
with a proposed scope, process, details, etc:

[options="header,autowidth",cols="^0,^0,^0,^0,^0"]
|===
| SF | F | N | A | SA
| 29 | 6 | 1 | 0 | 0
|===

*Result*: strong consensus
