= WITHDRAWN: C++ Ecosystem International Standard
:copyright: Copyright {docyear} René Ferdinand Rivera Morell
:email: grafikrobot@gmail.com
:authors: René Ferdinand Rivera Morell, et al.
:audience: WG21
:revdate: {docdate}
:version-label!:
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 5
:source-highlighter: rouge
:source-language: c++
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:table-caption: Table

++++
<style>
include::../std-min.css[]
</style>
++++

Document number: :: ISO/IEC/JTC1/SC22/WG21/{revnumber}
Date: :: {revdate}
Audience: :: {audience}
Reply-to: ::
René Ferdinand Rivera Morell - _grafikrobot at gmail dot com_

== Abstract

We propose to publish an International Standard that specifies formats,
processes, definitions, and so on, that facilitates the interoperation of the
tools and systems that implement, and interface with, the {CPP} International
Standard (ISO/IEC 14882).

== Revision History

=== Revision 4 (December 2024)

Withdraw this and related papers.

=== Revision 0 (October 2022)

Initial text.

== Withdrawn

We hereby withdraw this paper from WG21 consideration. And hence are halting
current efforts to publish an Ecosystem IS within the WG21 group in the near
term.

After almost three years of work it has become apparent that the limitations of
WG21 and ISO are insurmountable in the near term. And continuing to use the
standards development process of WG21, and hence of ISO, would jeopardize the
timeline and accessibility goals of our efforts.

We will continue development of the Ecosystem standard externally.
footnote:[https://github.com/ecostd]
We will consider making the Ecosystem standard available through ISO, and other
standards bodies, at a future time.
